Controllers/MemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Migrations.Operations;
using Notes.Models;
using Notes.ViewModels;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Notes.Controllers
{
    [Authorize]
    public class MemoController : Controller
    {
        private readonly IMemoRepository _memoRepository;

        public MemoController(IMemoRepository memoRepository)
        {
            _memoRepository = memoRepository;
        }

        public IActionResult Index()
        {
            var notes = _memoRepository.LoadAllNotes();
            var lists = _memoRepository.LoadAllLists();
            var items = _memoRepository.LoadAllItems();
            var memoVM = new MemoVM
            {
                Notes = notes.ToList(),
                Lists = lists.ToList(),
                Items = items.ToList()
            };

            return View("Index", memoVM);
        }

        public IActionResult CreateList(string title)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List list = new List { Title = title, IdentityUserId = userId };
            _memoRepository.AddList(list);

            return Json(new
            {
                success = true,
                data = list.Id
            });
        }

        public IActionResult CreateNote(string title, string text)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            Note note = new Note { Title = title, Text = text, IdentityUserId = userId };
            _memoRepository.AddNote(note);

            return Json(new
            {
                success = true,
                data = note.Id
            });
        }

        public IActionResult CreateItem(int listId, string itemtext)
        {
            Item item = new Item { ListId = listId, Text = itemtext, Checked = false };
            _memoRepository.AddItem(item);

            return Json(new
                {
                success = true,
                    data = item.Id
                  
            });
        }

        public IActionResult EditNote(int id, string text, string title)
        {
            _memoRepository.EditNote(id, text, title);

            return Json(new
            {
                success = true
            });

        }

        public IActionResult EditList(int id, string title)
        {
            _memoRepository.EditList(id, title);

            return Json(new
            {
                success = true
            });

        }

        public IActionResult EditItem(int id, string itemtext)
        {
            _memoRepository.EditItem(id, itemtext);

            return Json(
                new
                {
                    success = true
                });
        }

        public IActionResult Delete(int id)
        {
            var memo = _memoRepository.LoadMemoById(id);
            _memoRepository.Delete(memo);

            return Json(new
            {
                success = true,
            });

        }
        public IActionResult DeleteItem(int id)
        {
            var item = _memoRepository.LoadItemById(id);
            _memoRepository.DeleteItem(item);

            return Json(new
            {
                success = true,
            });
                
        }

        public IActionResult UnCheck(int id)
        {
            _memoRepository.UnCheckItem(id);

            return Json(new
            {
                success = true,
            });
            
        }

        public IActionResult Check(int id)
        {
            _memoRepository.CheckItem(id);

            return Json(new
            {
                success = true,
            });
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
@inject SignInManager<IdentityUser> SignInManager


<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="~/bootstrap/css/bootstrap-minty.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/StyleSheet.css" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet">
    <link href="~/css/all.css" rel="stylesheet">

    <script src="~/jquery/jquery-3.4.1.min.js"></script>
    <script src="~/bootstrap/js/bootstrap.bundle.min.js"></script>

</head>

<body>
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary" style="">
        <div class="container">
            @if (SignInManager.IsSignedIn(User))
            {
                <a asp-controller="Memo" asp-action="Index" class="navbar-brand">
                    <i class="far fa-clipboard" style="padding:10px"></i>Note
                </a>
            }
            @if (!SignInManager.IsSignedIn(User))
            {
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">
                    <i class="far fa-clipboard" style="padding:10px"></i>Note
                </a>

            }
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="themes" aria-expanded="false">Add<span class="caret"></span></a>
                            <div class="dropdown-menu" aria-labelledby="themes">
                                <a class="dropdown-item add" data-discriminator="note">Note</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item add" data-discriminator="list">List</a>

                            </div>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link" href="#">Help</a>
                    </li>

                </ul>

                <div class="navbar-nav ml-auto">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a class="nav-link">
                            Witaj, @User.Identity.Name
                        </a>

                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" id="search" type="text" placeholder="Search">
                            <button class="btn btn-secondary my-2 my-sm-0" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                        </form>
                        <a class="nav-link" href="#"><i class="far fa-user"></i></a>
                    }
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" id="logoutForm" method="post" class="navbar-right">
                                    <a class="nav-link" href="javascript:document.getElementById('logoutForm').submit()">Wyloguj</a>
                                </form>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </div>
    </div>

    <div class="container">

        @RenderBody()

    </div>
    <script type="text/template" id="templatenote">
        <div class="col-lg-3 elementnote">
            <div class=" card mb-3" data-memo-id="0">

                <div class="card-header text-white bg-primary" style="min-height: 50px">
                    <div class="editable notetitle" style="float: left;">Add title</div>
                    <a class="btn btn-primary savenote far fa-save" style="float:right; display: none" role="button"></a>
                    <a class="btn btn-primary delete far fa-trash-alt" data-toggle="modal" data-target="#deleteModal" style="float: right" role="button"></a>
                </div>

                <div class="card-body overflow-auto text">
                    <p class="card-text editable notetext" style="min-height: 10px">Add text</p>
                </div>
            </div>
        </div>
    </script>

    <script type="text/template" id="templatelist">
        <div class="col-lg-3">
            <div class=" card mb-3" style="max-width: 20rem;" data-memo-id="0">
                <div class="card-header text-white bg-primary" style="min-height: 50px">
                    <div class="editable listtitle" style="float: left">Add title</div>
                    <a class="btn btn-primary delete far fa-trash-alt" data-toggle="modal" data-target="#deleteModal" style="float: right" role="button"></a>
                    <a class="btn btn-primary fas fa-plus additem" role="button" style="float: right; display:none"></a>
                </div>
                <div class="card-body listcard">
                    <ul class="list-group overflow-auto text-black-50 items">
                    </ul>
                </div>
            </div>
        </div>
    </script>
    <script>

        var searchfunction = function () {

            var value = $(this).val().toLowerCase();
            $(".editable").filter(function () {
                var element = $(this).text().toLowerCase().indexOf(value) > -1
                $(this).toggle(element);
            });
        };

        var addmemofunction = function () {

            var discriminator = $(event.target).data("discriminator");
            var count = $(".card[data-memo-id=0]").length;
            if (count > 0) {
                $(".card[data-memo-id=0]").find('div.editable').click();
            }
            else {
                if (discriminator == "note") {
                    var blank = $($("#templatenote").html());
                    $("#notes").append(blank);
                    $('.editable', blank).click(editfunction);
                    $('.notetitle, .notetext', blank).blur(savenotefunction);
                    $('.delete', blank).click(deletefunction);
                }
                else {
                    var blank = $($("#templatelist").html());
                    $("#notes").append(blank);
                    $('.editable', blank).click(editfunction);
                    $('.listtitle', blank).blur(savelistfunction);
                    $('.delete', blank).click(deletefunction);
                    $('.additem', blank).click(additemfunction);
                }
            }
        }

        $(document).ready(function () {
            $("#search").on("keyup", searchfunction);
            $("a.add").click(addmemofunction);
        });

    </script>

</body>

</html>